Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: notesTable
      AttributeDefinitions:
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: noteId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5